 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
       - run: npm test
       - run: ./deploy.sh
