 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login
       - run: npm test
       - run: ./deploy.sh
