 version: 2.1
 jobs:
   build:
     docker:
       - image: cimg/node:17.2.0
     steps:
       - checkout
       - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
       - run: npm test
       - run: ./deploy.sh
